{"ip":"192.168.3.255","data":{"tls":{"status":"unknown-error","protocol":"tls","timestamp":"2025-05-23T08:26:40Z","error":"failed to dial target 192.168.3.255: could not initiate a L4 connection with L4 dialer: dial context failed: dial tcp 192.168.3.255:443: connect: connection refused"}}}
